<?php

return [
    'job_landing_pages' => [
        'bank-mandiri' => [
            'title' => 'Lowongan Bank Mandiri Terbaru - Lamaraja',
            'heading' => 'Lowongan Bank Mandiri',
            'description' => 'Cari lowongan Bank Mandiri dan peluang kerja perbankan terbaru yang terkurasi di Lamaraja.',
            'keyword' => 'bank mandiri',
            'intro' => 'Kumpulan peluang kerja Bank Mandiri dan posisi perbankan terkait. Gunakan CV Matcher untuk cek kecocokan sebelum melamar.',
            'related' => ['admin', 'fresh-graduate', 'magang'],
        ],
        'admin-bekasi' => [
            'title' => 'Loker Admin Bekasi Terbaru - Lamaraja',
            'heading' => 'Loker Admin Bekasi',
            'description' => 'Temukan loker admin di Bekasi dan sekitarnya dari berbagai sumber terpercaya.',
            'keyword' => 'admin',
            'location' => 'bekasi',
            'intro' => 'Halaman ini mengkurasi peluang kerja admin di Bekasi agar kandidat bisa menemukan lowongan relevan lebih cepat.',
            'related' => ['admin', 'customer-service', 'fresh-graduate'],
        ],
        'collector-lapangan' => [
            'title' => 'Lowongan Collector Lapangan Terbaru - Lamaraja',
            'heading' => 'Lowongan Collector Lapangan',
            'description' => 'Cari lowongan collector lapangan terbaru, termasuk peluang kerja field collection dan operasional terkait.',
            'keyword' => 'collector lapangan',
            'intro' => 'Peluang kerja collector lapangan yang aktif dan mudah dibandingkan sebelum melamar.',
            'related' => ['sales', 'operasional', 'sma-smk'],
        ],
        'remote' => [
            'title' => 'Lowongan Kerja Remote Terbaru - Lamaraja',
            'heading' => 'Lowongan Kerja Remote',
            'description' => 'Temukan lowongan remote dan hybrid terbaru untuk kandidat Indonesia.',
            'keyword' => 'remote',
            'intro' => 'Kumpulan lowongan remote dan hybrid untuk kandidat yang ingin bekerja fleksibel dari Indonesia.',
            'related' => ['it', 'part-time', 'customer-service'],
        ],
        'fresh-graduate' => [
            'title' => 'Lowongan Fresh Graduate Terbaru - Lamaraja',
            'heading' => 'Lowongan Fresh Graduate',
            'description' => 'Cari lowongan fresh graduate terbaru untuk mulai karier pertama dengan lebih percaya diri.',
            'keyword' => 'fresh graduate',
            'intro' => 'Kurasi lowongan fresh graduate aktif untuk kandidat awal karier. Upload CV sekali, lalu gunakan CV Matcher untuk menemukan peluang yang paling cocok.',
            'related' => ['magang', 'sma-smk', 'admin'],
        ],
        'magang' => [
            'title' => 'Lowongan Magang Terbaru - Lamaraja',
            'heading' => 'Lowongan Magang',
            'description' => 'Temukan lowongan magang dan internship terbaru dari perusahaan yang sedang membuka peluang untuk mahasiswa dan fresh graduate.',
            'keyword' => 'intern',
            'employment_type' => ['internship'],
            'intro' => 'Kumpulan lowongan magang aktif untuk membangun pengalaman kerja pertama. Bandingkan ringkasan AI dan cek kecocokan CV sebelum melamar.',
            'related' => ['fresh-graduate', 'part-time', 'admin'],
        ],
        'admin' => [
            'title' => 'Lowongan Admin Terbaru - Lamaraja',
            'heading' => 'Lowongan Admin',
            'description' => 'Cari lowongan admin terbaru untuk posisi administrasi, operasional kantor, dan back office.',
            'keyword' => 'admin',
            'intro' => 'Kumpulan loker admin aktif dari berbagai kota. Bandingkan requirement dan cek kecocokan CV sebelum melamar.',
            'related' => ['admin-bekasi', 'customer-service', 'fresh-graduate'],
        ],
        'akuntansi' => [
            'title' => 'Lowongan Akuntansi Terbaru - Lamaraja',
            'heading' => 'Lowongan Akuntansi',
            'description' => 'Temukan lowongan akuntansi, finance, accounting staff, dan posisi keuangan terbaru.',
            'keyword' => 'akuntansi',
            'intro' => 'Peluang kerja akuntansi dan finance yang aktif untuk kandidat entry-level hingga berpengalaman.',
            'related' => ['admin', 'fresh-graduate'],
        ],
        'sales' => [
            'title' => 'Lowongan Sales Terbaru - Lamaraja',
            'heading' => 'Lowongan Sales',
            'description' => 'Cari lowongan sales, account executive, business development, dan posisi penjualan terbaru.',
            'keyword' => 'sales',
            'intro' => 'Kurasi peluang kerja sales dan business development dengan ringkasan cepat agar mudah dibandingkan.',
            'related' => ['marketing', 'collector-lapangan', 'customer-service'],
        ],
        'customer-service' => [
            'title' => 'Lowongan Customer Service Terbaru - Lamaraja',
            'heading' => 'Lowongan Customer Service',
            'description' => 'Temukan loker customer service, call center, dan support pelanggan terbaru.',
            'keyword' => 'customer service',
            'intro' => 'Cari peluang customer service aktif dan gunakan CV Matcher untuk melihat kecocokan skill komunikasimu.',
            'related' => ['admin', 'remote', 'fresh-graduate'],
        ],
        'marketing' => [
            'title' => 'Lowongan Marketing Terbaru - Lamaraja',
            'heading' => 'Lowongan Marketing',
            'description' => 'Cari lowongan marketing, digital marketing, campaign, dan brand terbaru.',
            'keyword' => 'marketing',
            'intro' => 'Kurasi lowongan marketing aktif untuk kandidat kreatif, analitis, dan komunikatif.',
            'related' => ['sales', 'it', 'fresh-graduate'],
        ],
        'it' => [
            'title' => 'Lowongan IT Terbaru - Lamaraja',
            'heading' => 'Lowongan IT',
            'description' => 'Temukan lowongan IT, developer, data, product, dan teknologi terbaru.',
            'keyword' => 'it',
            'intro' => 'Kumpulan peluang kerja IT aktif, termasuk role teknis dan digital yang bisa kamu bandingkan cepat.',
            'related' => ['remote', 'marketing', 'fresh-graduate'],
        ],
        'guru' => [
            'title' => 'Lowongan Guru Terbaru - Lamaraja',
            'heading' => 'Lowongan Guru',
            'description' => 'Cari lowongan guru, tutor, pengajar, dan posisi edukasi terbaru.',
            'keyword' => 'guru',
            'intro' => 'Temukan peluang mengajar aktif dan lihat requirement utama sebelum mengirim lamaran.',
            'related' => ['fresh-graduate', 'part-time'],
        ],
        'operasional' => [
            'title' => 'Lowongan Operasional Terbaru - Lamaraja',
            'heading' => 'Lowongan Operasional',
            'description' => 'Cari loker operasional, staff lapangan, warehouse, dan posisi support bisnis terbaru.',
            'keyword' => 'operasional',
            'intro' => 'Kurasi lowongan operasional aktif untuk kandidat yang siap bekerja di lapangan maupun kantor.',
            'related' => ['logistik', 'collector-lapangan', 'sma-smk'],
        ],
        'logistik' => [
            'title' => 'Lowongan Logistik Terbaru - Lamaraja',
            'heading' => 'Lowongan Logistik',
            'description' => 'Temukan lowongan logistik, warehouse, supply chain, dan pengiriman terbaru.',
            'keyword' => 'logistik',
            'intro' => 'Peluang kerja logistik dan gudang yang aktif dari berbagai sumber terpercaya.',
            'related' => ['operasional', 'sma-smk'],
        ],
        'sma-smk' => [
            'title' => 'Lowongan SMA/SMK Terbaru - Lamaraja',
            'heading' => 'Lowongan SMA/SMK',
            'description' => 'Cari lowongan kerja untuk lulusan SMA/SMK terbaru dari berbagai bidang.',
            'keyword' => 'sma smk',
            'intro' => 'Kumpulan loker untuk lulusan SMA/SMK yang aktif dan mudah dibandingkan sebelum melamar.',
            'related' => ['fresh-graduate', 'operasional', 'admin'],
        ],
        'part-time' => [
            'title' => 'Lowongan Part Time Terbaru - Lamaraja',
            'heading' => 'Lowongan Part Time',
            'description' => 'Temukan lowongan part time, freelance, dan kerja fleksibel terbaru.',
            'keyword' => 'part time',
            'employment_type' => ['part-time'],
            'intro' => 'Cari pekerjaan part time aktif untuk mahasiswa, fresh graduate, dan kandidat yang butuh jadwal fleksibel.',
            'related' => ['magang', 'remote', 'guru'],
        ],
    ],
];
